// <auto-generated />
using System;
using FreshOMill.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FreshOMill.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260803191417_AddProducts")]
    partial class AddProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FreshOMill.Domain.Catalog.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0a80001-0000-0000-0000-000000000001"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 1,
                            ImageUrl = "/images/categories/wood-pressed-oils.jpg",
                            Name = "Wood Pressed Oils",
                            Slug = "wood-pressed-oils"
                        },
                        new
                        {
                            Id = new Guid("c0a80001-0000-0000-0000-000000000002"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 2,
                            ImageUrl = "/images/categories/flour-multigrain.jpg",
                            Name = "Flour & Multigrain",
                            Slug = "flour-multigrain"
                        },
                        new
                        {
                            Id = new Guid("c0a80001-0000-0000-0000-000000000003"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 3,
                            ImageUrl = "/images/categories/dry-fruits-dates.jpg",
                            Name = "Dry Fruits & Dates",
                            Slug = "dry-fruits-dates"
                        },
                        new
                        {
                            Id = new Guid("c0a80001-0000-0000-0000-000000000004"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 4,
                            ImageUrl = "/images/categories/nuts-seeds.jpg",
                            Name = "Nuts & Seeds",
                            Slug = "nuts-seeds"
                        },
                        new
                        {
                            Id = new Guid("c0a80001-0000-0000-0000-000000000005"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 5,
                            ImageUrl = "/images/categories/millets.jpg",
                            Name = "Millets",
                            Slug = "millets"
                        },
                        new
                        {
                            Id = new Guid("c0a80001-0000-0000-0000-000000000006"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 6,
                            ImageUrl = "/images/categories/spices.jpg",
                            Name = "Spices",
                            Slug = "spices"
                        },
                        new
                        {
                            Id = new Guid("c0a80001-0000-0000-0000-000000000007"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 7,
                            ImageUrl = "/images/categories/masalas.jpg",
                            Name = "Masalas",
                            Slug = "masalas"
                        },
                        new
                        {
                            Id = new Guid("c0a80001-0000-0000-0000-000000000008"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 8,
                            ImageUrl = "/images/categories/health-foods.jpg",
                            Name = "Health Foods",
                            Slug = "health-foods"
                        },
                        new
                        {
                            Id = new Guid("c0a80001-0000-0000-0000-000000000009"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 9,
                            ImageUrl = "/images/categories/coffee-tea.jpg",
                            Name = "Coffee & Tea",
                            Slug = "coffee-tea"
                        },
                        new
                        {
                            Id = new Guid("c0a80001-0000-0000-0000-000000000010"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 10,
                            ImageUrl = "/images/categories/pickles.jpg",
                            Name = "Pickles",
                            Slug = "pickles"
                        },
                        new
                        {
                            Id = new Guid("c0a80001-0000-0000-0000-000000000011"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 11,
                            ImageUrl = "/images/categories/rice-grains.jpg",
                            Name = "Rice & Grains",
                            Slug = "rice-grains"
                        },
                        new
                        {
                            Id = new Guid("c0a80001-0000-0000-0000-000000000012"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 12,
                            ImageUrl = "/images/categories/ghee-dairy.jpg",
                            Name = "Ghee & Dairy",
                            Slug = "ghee-dairy"
                        },
                        new
                        {
                            Id = new Guid("c0a80001-0000-0000-0000-000000000013"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 13,
                            ImageUrl = "/images/categories/honey-jaggery.jpg",
                            Name = "Honey & Jaggery",
                            Slug = "honey-jaggery"
                        },
                        new
                        {
                            Id = new Guid("c0a80001-0000-0000-0000-000000000014"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 14,
                            ImageUrl = "/images/categories/herbal-wellness.jpg",
                            Name = "Herbal & Wellness",
                            Slug = "herbal-wellness"
                        },
                        new
                        {
                            Id = new Guid("c0a80001-0000-0000-0000-000000000015"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 15,
                            ImageUrl = "/images/categories/snacks-namkeen.jpg",
                            Name = "Snacks & Namkeen",
                            Slug = "snacks-namkeen"
                        });
                });

            modelBuilder.Entity("FreshOMill.Domain.Catalog.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("InStock")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Popularity")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000001"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000001"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Cold, wood-pressed from farm-fresh coconut kernels — no heat, no solvents, no refining.",
                            ImageUrl = "/images/products/wood-pressed-oils/coconut-oil.jpg",
                            InStock = true,
                            Name = "Coconut Oil",
                            Popularity = 1,
                            Price = 360m,
                            Slug = "coconut-oil",
                            Unit = "500ml"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000002"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000001"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Pungent, kachi-ghani mustard oil pressed in small batches at low temperature.",
                            ImageUrl = "/images/products/wood-pressed-oils/mustard-oil.jpg",
                            InStock = true,
                            Name = "Mustard Oil",
                            Popularity = 6,
                            Price = 320m,
                            Slug = "mustard-oil",
                            Unit = "500ml"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000003"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000001"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Rich, nutty groundnut oil wood-pressed the traditional ghani way for everyday cooking.",
                            ImageUrl = "/images/products/wood-pressed-oils/groundnut-oil.jpg",
                            InStock = true,
                            Name = "Groundnut Oil",
                            Popularity = 9,
                            Price = 280m,
                            Slug = "groundnut-oil",
                            Unit = "1L"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000004"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000001"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Stone-pressed sesame oil with a deep, toasty aroma — a South Indian kitchen staple.",
                            ImageUrl = "/images/products/wood-pressed-oils/sesame-oil.jpg",
                            InStock = true,
                            Name = "Sesame Oil",
                            Popularity = 12,
                            Price = 340m,
                            Slug = "sesame-oil",
                            Unit = "500ml"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000005"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000001"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Light, wood-pressed sunflower oil that keeps every dish tasting clean and fresh.",
                            ImageUrl = "/images/products/wood-pressed-oils/sunflower-oil.jpg",
                            InStock = true,
                            Name = "Sunflower Oil",
                            Popularity = 15,
                            Price = 260m,
                            Slug = "sunflower-oil",
                            Unit = "1L"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000006"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000002"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "100% stone-ground whole wheat atta, milled fresh strictly after your order is placed.",
                            ImageUrl = "/images/products/flour-multigrain/chakki-fresh-atta.jpg",
                            InStock = true,
                            Name = "Chakki Fresh Atta",
                            Popularity = 16,
                            Price = 280m,
                            Slug = "chakki-fresh-atta",
                            Unit = "1kg"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000007"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000002"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "A wholesome blend of wheat, jowar, bajra and ragi ground together into one flour.",
                            ImageUrl = "/images/products/flour-multigrain/multigrain-atta.jpg",
                            InStock = true,
                            Name = "Multigrain Atta",
                            Popularity = 21,
                            Price = 310m,
                            Slug = "multigrain-atta",
                            Unit = "1kg"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000008"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000002"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Finger millet flour, naturally rich in calcium — stone-ground for a fine, even texture.",
                            ImageUrl = "/images/products/flour-multigrain/ragi-flour.jpg",
                            InStock = false,
                            Name = "Ragi Flour",
                            Popularity = 24,
                            Price = 180m,
                            Slug = "ragi-flour",
                            Unit = "500g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000009"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000002"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Sorghum flour milled fresh for soft, gluten-free rotis and bhakri.",
                            ImageUrl = "/images/products/flour-multigrain/jowar-flour.jpg",
                            InStock = true,
                            Name = "Jowar Flour",
                            Popularity = 27,
                            Price = 190m,
                            Slug = "jowar-flour",
                            Unit = "500g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000010"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000002"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Pearl millet flour, stone-ground for a warming winter staple with a distinct earthy taste.",
                            ImageUrl = "/images/products/flour-multigrain/bajra-flour.jpg",
                            InStock = true,
                            Name = "Bajra Flour",
                            Popularity = 30,
                            Price = 170m,
                            Slug = "bajra-flour",
                            Unit = "500g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000011"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000003"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Soft, caramel-sweet premium dates hand-picked and packed at peak freshness.",
                            ImageUrl = "/images/products/dry-fruits-dates/premium-dates.jpg",
                            InStock = true,
                            Name = "Premium Dates",
                            Popularity = 31,
                            Price = 420m,
                            Slug = "premium-dates",
                            Unit = "500g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000012"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000003"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Sun-dried apricots with a tangy-sweet bite, naturally preserved with no added sugar.",
                            ImageUrl = "/images/products/dry-fruits-dates/dried-apricots.jpg",
                            InStock = true,
                            Name = "Dried Apricots",
                            Popularity = 36,
                            Price = 480m,
                            Slug = "dried-apricots",
                            Unit = "250g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000013"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000003"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Plump, naturally sun-dried figs — a fibre-rich snack straight from the orchard.",
                            ImageUrl = "/images/products/dry-fruits-dates/dried-figs.jpg",
                            InStock = true,
                            Name = "Dried Figs",
                            Popularity = 39,
                            Price = 550m,
                            Slug = "dried-figs",
                            Unit = "250g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000014"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000003"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Seedless golden raisins, sun-dried for a naturally sweet, chewy everyday snack.",
                            ImageUrl = "/images/products/dry-fruits-dates/raisins.jpg",
                            InStock = true,
                            Name = "Raisins",
                            Popularity = 42,
                            Price = 220m,
                            Slug = "raisins",
                            Unit = "250g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000015"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000003"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Tart-sweet dried cranberries, great over salads, cereal or eaten straight from the pack.",
                            ImageUrl = "/images/products/dry-fruits-dates/dried-cranberries.jpg",
                            InStock = true,
                            Name = "Dried Cranberries",
                            Popularity = 45,
                            Price = 380m,
                            Slug = "dried-cranberries",
                            Unit = "200g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000016"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000004"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Bold, California-grade almonds sorted for size and freshness in every batch.",
                            ImageUrl = "/images/products/nuts-seeds/almonds-premium.jpg",
                            InStock = false,
                            Name = "Almonds Premium",
                            Popularity = 46,
                            Price = 950m,
                            Slug = "almonds-premium",
                            Unit = "500g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000017"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000004"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Whole, creamy cashews (W240 grade) roasted fresh to order in small batches.",
                            ImageUrl = "/images/products/nuts-seeds/cashew-nuts.jpg",
                            InStock = true,
                            Name = "Cashew Nuts",
                            Popularity = 51,
                            Price = 1200m,
                            Slug = "cashew-nuts",
                            Unit = "500g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000018"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000004"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Whole walnut kernels, light and buttery — a daily source of good fats.",
                            ImageUrl = "/images/products/nuts-seeds/walnuts.jpg",
                            InStock = true,
                            Name = "Walnuts",
                            Popularity = 54,
                            Price = 1100m,
                            Slug = "walnuts",
                            Unit = "500g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000019"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000004"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Roasted, lightly salted pistachios shelled and packed for maximum crunch.",
                            ImageUrl = "/images/products/nuts-seeds/pistachios.jpg",
                            InStock = true,
                            Name = "Pistachios",
                            Popularity = 57,
                            Price = 1350m,
                            Slug = "pistachios",
                            Unit = "500g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000020"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000004"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Cleaned, hulled white sesame seeds — a nutty finish for chikki, chutneys and baking.",
                            ImageUrl = "/images/products/nuts-seeds/sesame-seeds.jpg",
                            InStock = true,
                            Name = "Sesame Seeds",
                            Popularity = 60,
                            Price = 280m,
                            Slug = "sesame-seeds",
                            Unit = "500g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000021"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000005"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Whole organic pearl millet grain, sourced from certified organic farms.",
                            ImageUrl = "/images/products/millets/organic-bajra.jpg",
                            InStock = true,
                            Name = "Organic Bajra",
                            Popularity = 61,
                            Price = 150m,
                            Slug = "organic-bajra",
                            Unit = "500g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000022"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000005"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "A light, easy-to-digest ancient grain — swaps in for rice in any everyday meal.",
                            ImageUrl = "/images/products/millets/foxtail-millet.jpg",
                            InStock = true,
                            Name = "Foxtail Millet",
                            Popularity = 66,
                            Price = 160m,
                            Slug = "foxtail-millet",
                            Unit = "500g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000023"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000005"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "A high-fibre millet with a mild, nutty flavour, ideal for pulao and khichdi.",
                            ImageUrl = "/images/products/millets/kodo-millet.jpg",
                            InStock = true,
                            Name = "Kodo Millet",
                            Popularity = 69,
                            Price = 155m,
                            Slug = "kodo-millet",
                            Unit = "500g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000024"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000005"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Small-grained, quick-cooking millet — a light everyday substitute for rice.",
                            ImageUrl = "/images/products/millets/little-millet.jpg",
                            InStock = false,
                            Name = "Little Millet",
                            Popularity = 72,
                            Price = 145m,
                            Slug = "little-millet",
                            Unit = "500g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000025"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000005"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "A fasting-friendly millet with a soft texture, popular in upma and porridge.",
                            ImageUrl = "/images/products/millets/barnyard-millet.jpg",
                            InStock = true,
                            Name = "Barnyard Millet",
                            Popularity = 75,
                            Price = 165m,
                            Slug = "barnyard-millet",
                            Unit = "500g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000026"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000006"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Sun-dried, stone-ground organic turmeric with a deep golden colour and aroma.",
                            ImageUrl = "/images/products/spices/organic-turmeric.jpg",
                            InStock = true,
                            Name = "Organic Turmeric",
                            Popularity = 76,
                            Price = 180m,
                            Slug = "organic-turmeric",
                            Unit = "250g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000027"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000006"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Bright red, medium-hot chilli powder ground fresh from sun-dried whole chillies.",
                            ImageUrl = "/images/products/spices/red-chilli-powder.jpg",
                            InStock = true,
                            Name = "Red Chilli Powder",
                            Popularity = 81,
                            Price = 200m,
                            Slug = "red-chilli-powder",
                            Unit = "250g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000028"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000006"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Freshly ground coriander seeds with a warm, citrusy aroma for everyday curries.",
                            ImageUrl = "/images/products/spices/coriander-powder.jpg",
                            InStock = true,
                            Name = "Coriander Powder",
                            Popularity = 84,
                            Price = 160m,
                            Slug = "coriander-powder",
                            Unit = "200g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000029"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000006"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Whole, aromatic cumin seeds — cleaned and sorted for a strong, earthy tempering.",
                            ImageUrl = "/images/products/spices/cumin-seeds.jpg",
                            InStock = true,
                            Name = "Cumin Seeds",
                            Popularity = 87,
                            Price = 350m,
                            Slug = "cumin-seeds",
                            Unit = "500g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000030"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000006"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Bold, sun-dried whole black peppercorns with a sharp, pungent bite.",
                            ImageUrl = "/images/products/spices/black-pepper.jpg",
                            InStock = true,
                            Name = "Black Pepper",
                            Popularity = 90,
                            Price = 420m,
                            Slug = "black-pepper",
                            Unit = "200g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000031"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000007"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "A warm, aromatic blend of roasted whole spices ground fresh in small batches.",
                            ImageUrl = "/images/products/masalas/garam-masala.jpg",
                            InStock = true,
                            Name = "Garam Masala",
                            Popularity = 91,
                            Price = 220m,
                            Slug = "garam-masala",
                            Unit = "200g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000032"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000007"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "A tangy, robust spice mix built specifically for chickpea curries.",
                            ImageUrl = "/images/products/masalas/chana-masala.jpg",
                            InStock = false,
                            Name = "Chana Masala",
                            Popularity = 96,
                            Price = 190m,
                            Slug = "chana-masala",
                            Unit = "200g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000033"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000007"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "A South Indian lentil-stew spice blend with a distinct roasted-dal aroma.",
                            ImageUrl = "/images/products/masalas/sambar-masala.jpg",
                            InStock = true,
                            Name = "Sambar Masala",
                            Popularity = 99,
                            Price = 210m,
                            Slug = "sambar-masala",
                            Unit = "200g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000034"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000007"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "A tangy, black-salt forward mix that finishes fruit chaat, snacks and salads.",
                            ImageUrl = "/images/products/masalas/chaat-masala.jpg",
                            InStock = true,
                            Name = "Chaat Masala",
                            Popularity = 102,
                            Price = 180m,
                            Slug = "chaat-masala",
                            Unit = "200g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000035"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000007"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "A bold, tomato-friendly spice blend made for classic street-style pav bhaji.",
                            ImageUrl = "/images/products/masalas/pav-bhaji-masala.jpg",
                            InStock = true,
                            Name = "Pav Bhaji Masala",
                            Popularity = 105,
                            Price = 200m,
                            Slug = "pav-bhaji-masala",
                            Unit = "200g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000036"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000008"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Steam-rolled whole oats — a quick, fibre-rich breakfast base.",
                            ImageUrl = "/images/products/health-foods/rolled-oats.jpg",
                            InStock = true,
                            Name = "Rolled Oats",
                            Popularity = 106,
                            Price = 240m,
                            Slug = "rolled-oats",
                            Unit = "500g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000037"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000008"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Tiny, omega-3 rich chia seeds that swell into a gel — great in smoothies and puddings.",
                            ImageUrl = "/images/products/health-foods/chia-seeds.jpg",
                            InStock = true,
                            Name = "Chia Seeds",
                            Popularity = 111,
                            Price = 380m,
                            Slug = "chia-seeds",
                            Unit = "250g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000038"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000008"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Rich in alpha-linolenic acid, these seeds support heart and brain health.",
                            ImageUrl = "/images/products/health-foods/flax-seeds.jpg",
                            InStock = true,
                            Name = "Flax Seeds",
                            Popularity = 114,
                            Price = 260m,
                            Slug = "flax-seeds",
                            Unit = "250g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000039"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000008"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Shade-dried moringa leaves ground into a fine, nutrient-dense green powder.",
                            ImageUrl = "/images/products/health-foods/moringa-powder.jpg",
                            InStock = false,
                            Name = "Moringa Powder",
                            Popularity = 120,
                            Price = 320m,
                            Slug = "moringa-powder",
                            Unit = "200g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000040"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000009"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "A classic South Indian coffee-chicory blend, roasted and ground for filter brewing.",
                            ImageUrl = "/images/products/coffee-tea/filter-coffee-powder.jpg",
                            InStock = true,
                            Name = "Filter Coffee Powder",
                            Popularity = 121,
                            Price = 280m,
                            Slug = "filter-coffee-powder",
                            Unit = "500g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000041"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000009"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Whole-leaf green tea with a light, grassy character and gentle antioxidant lift.",
                            ImageUrl = "/images/products/coffee-tea/green-tea.jpg",
                            InStock = true,
                            Name = "Green Tea",
                            Popularity = 126,
                            Price = 320m,
                            Slug = "green-tea",
                            Unit = "100g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000042"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000009"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Robust CTC tea leaves pre-blended with warming whole spices for a strong chai.",
                            ImageUrl = "/images/products/coffee-tea/masala-chai.jpg",
                            InStock = true,
                            Name = "Masala Chai",
                            Popularity = 129,
                            Price = 240m,
                            Slug = "masala-chai",
                            Unit = "250g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000043"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000009"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "A caffeine-free infusion of dried herbs and flowers for a calming cup any time of day.",
                            ImageUrl = "/images/products/coffee-tea/herbal-tea.jpg",
                            InStock = true,
                            Name = "Herbal Tea",
                            Popularity = 132,
                            Price = 260m,
                            Slug = "herbal-tea",
                            Unit = "100g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000044"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000009"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Freeze-dried instant coffee granules for a quick, rich cup with no brewing needed.",
                            ImageUrl = "/images/products/coffee-tea/instant-coffee.jpg",
                            InStock = true,
                            Name = "Instant Coffee",
                            Popularity = 135,
                            Price = 350m,
                            Slug = "instant-coffee",
                            Unit = "200g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000045"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000010"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Raw mango pickled in mustard oil with a bold, tangy-spiced masala.",
                            ImageUrl = "/images/products/pickles/mango-pickle.jpg",
                            InStock = true,
                            Name = "Mango Pickle",
                            Popularity = 136,
                            Price = 220m,
                            Slug = "mango-pickle",
                            Unit = "400g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000046"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000010"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Sun-cured lemons pickled whole for a sharp, tangy everyday side.",
                            ImageUrl = "/images/products/pickles/lemon-pickle.jpg",
                            InStock = true,
                            Name = "Lemon Pickle",
                            Popularity = 141,
                            Price = 200m,
                            Slug = "lemon-pickle",
                            Unit = "400g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000047"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000010"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Carrot, cauliflower and turnip pickled together in a robust spiced oil.",
                            ImageUrl = "/images/products/pickles/mixed-veg-pickle.jpg",
                            InStock = false,
                            Name = "Mixed Veg Pickle",
                            Popularity = 144,
                            Price = 240m,
                            Slug = "mixed-veg-pickle",
                            Unit = "400g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000048"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000010"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Whole garlic cloves slow-pickled in a fiery, richly spiced masala.",
                            ImageUrl = "/images/products/pickles/garlic-pickle.jpg",
                            InStock = true,
                            Name = "Garlic Pickle",
                            Popularity = 147,
                            Price = 230m,
                            Slug = "garlic-pickle",
                            Unit = "400g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000049"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000010"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Whole green chillies pickled hot and tangy — not for the faint-hearted.",
                            ImageUrl = "/images/products/pickles/chilli-pickle.jpg",
                            InStock = true,
                            Name = "Chilli Pickle",
                            Popularity = 150,
                            Price = 210m,
                            Slug = "chilli-pickle",
                            Unit = "400g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000050"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000011"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Long-grain, aged basmati rice with a fragrant aroma and fluffy texture.",
                            ImageUrl = "/images/products/rice-grains/basmati-rice.jpg",
                            InStock = true,
                            Name = "Basmati Rice",
                            Popularity = 151,
                            Price = 320m,
                            Slug = "basmati-rice",
                            Unit = "1kg"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000051"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000011"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "A light, medium-grain everyday rice popular across South Indian kitchens.",
                            ImageUrl = "/images/products/rice-grains/sona-masoori-rice.jpg",
                            InStock = true,
                            Name = "Sona Masoori Rice",
                            Popularity = 156,
                            Price = 180m,
                            Slug = "sona-masoori-rice",
                            Unit = "1kg"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000052"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000011"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Unpolished whole-grain rice with its bran intact for extra fibre.",
                            ImageUrl = "/images/products/rice-grains/brown-rice.jpg",
                            InStock = true,
                            Name = "Brown Rice",
                            Popularity = 159,
                            Price = 210m,
                            Slug = "brown-rice",
                            Unit = "1kg"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000053"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000011"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Split, polished chana dal that cooks up soft with a mild, nutty taste.",
                            ImageUrl = "/images/products/rice-grains/chana-dal.jpg",
                            InStock = true,
                            Name = "Chana Dal",
                            Popularity = 162,
                            Price = 220m,
                            Slug = "chana-dal",
                            Unit = "1kg"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000054"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000011"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "The everyday dal for sambar and tadka — split, cleaned and unpolished.",
                            ImageUrl = "/images/products/rice-grains/toor-dal.jpg",
                            InStock = true,
                            Name = "Toor Dal",
                            Popularity = 165,
                            Price = 200m,
                            Slug = "toor-dal",
                            Unit = "1kg"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000055"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000012"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Slow-simmered, bilona-method cow ghee with a rich, grainy texture and aroma.",
                            ImageUrl = "/images/products/ghee-dairy/pure-cow-ghee.jpg",
                            InStock = false,
                            Name = "Pure Cow Ghee",
                            Popularity = 166,
                            Price = 650m,
                            Slug = "pure-cow-ghee",
                            Unit = "500ml"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000056"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000012"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "A2 desi cow milk ghee, hand-churned the traditional bilona way.",
                            ImageUrl = "/images/products/ghee-dairy/a2-ghee.jpg",
                            InStock = true,
                            Name = "A2 Ghee",
                            Popularity = 171,
                            Price = 850m,
                            Slug = "a2-ghee",
                            Unit = "500ml"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000057"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000012"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Rich, dense buffalo milk ghee with a deep, full-bodied flavour.",
                            ImageUrl = "/images/products/ghee-dairy/buffalo-ghee.jpg",
                            InStock = true,
                            Name = "Buffalo Ghee",
                            Popularity = 174,
                            Price = 600m,
                            Slug = "buffalo-ghee",
                            Unit = "500ml"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000058"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000012"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Fresh, soft paneer set daily from full-cream milk.",
                            ImageUrl = "/images/products/ghee-dairy/paneer.jpg",
                            InStock = true,
                            Name = "Paneer",
                            Popularity = 177,
                            Price = 180m,
                            Slug = "paneer",
                            Unit = "200g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000059"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000012"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "A live curd starter culture for setting thick, creamy curd at home.",
                            ImageUrl = "/images/products/ghee-dairy/curd-culture.jpg",
                            InStock = true,
                            Name = "Curd Culture",
                            Popularity = 180,
                            Price = 90m,
                            Slug = "curd-culture",
                            Unit = "100g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000060"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000013"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Raw, unheated honey harvested from multi-floral forest sources.",
                            ImageUrl = "/images/products/honey-jaggery/pure-honey.jpg",
                            InStock = true,
                            Name = "Pure Honey",
                            Popularity = 181,
                            Price = 420m,
                            Slug = "pure-honey",
                            Unit = "500ml"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000061"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000013"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Chemical-free, sun-cured sugarcane jaggery with a deep caramel note.",
                            ImageUrl = "/images/products/honey-jaggery/organic-jaggery.jpg",
                            InStock = true,
                            Name = "Organic Jaggery",
                            Popularity = 186,
                            Price = 140m,
                            Slug = "organic-jaggery",
                            Unit = "1kg"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000062"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000013"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Free-flowing granulated jaggery powder — an easy 1:1 sugar swap.",
                            ImageUrl = "/images/products/honey-jaggery/jaggery-powder.jpg",
                            InStock = true,
                            Name = "Jaggery Powder",
                            Popularity = 189,
                            Price = 150m,
                            Slug = "jaggery-powder",
                            Unit = "500g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000063"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000013"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Wild forest honey, hand-harvested with a bold, distinct floral character.",
                            ImageUrl = "/images/products/honey-jaggery/forest-honey.jpg",
                            InStock = false,
                            Name = "Forest Honey",
                            Popularity = 192,
                            Price = 480m,
                            Slug = "forest-honey",
                            Unit = "500ml"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000064"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000013"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Traditional date palm jaggery with a smoky-sweet, molasses-like depth.",
                            ImageUrl = "/images/products/honey-jaggery/date-palm-jaggery.jpg",
                            InStock = true,
                            Name = "Date Palm Jaggery",
                            Popularity = 195,
                            Price = 180m,
                            Slug = "date-palm-jaggery",
                            Unit = "500g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000065"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000014"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Root-derived ashwagandha powder, sun-dried and stone-ground.",
                            ImageUrl = "/images/products/herbal-wellness/ashwagandha-powder.jpg",
                            InStock = true,
                            Name = "Ashwagandha Powder",
                            Popularity = 196,
                            Price = 350m,
                            Slug = "ashwagandha-powder",
                            Unit = "200g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000066"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000014"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Sun-dried Indian gooseberry ground into a tangy, vitamin-C rich powder.",
                            ImageUrl = "/images/products/herbal-wellness/amla-powder.jpg",
                            InStock = true,
                            Name = "Amla Powder",
                            Popularity = 201,
                            Price = 220m,
                            Slug = "amla-powder",
                            Unit = "200g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000067"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000014"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "A concentrated holy basil extract, a few drops added to warm water or tea.",
                            ImageUrl = "/images/products/herbal-wellness/tulsi-drops.jpg",
                            InStock = true,
                            Name = "Tulsi Drops",
                            Popularity = 204,
                            Price = 280m,
                            Slug = "tulsi-drops",
                            Unit = "30ml"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000068"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000014"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "A classic three-fruit Ayurvedic blend, stone-ground into a fine powder.",
                            ImageUrl = "/images/products/herbal-wellness/triphala-powder.jpg",
                            InStock = true,
                            Name = "Triphala Powder",
                            Popularity = 207,
                            Price = 240m,
                            Slug = "triphala-powder",
                            Unit = "200g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000069"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000014"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Encapsulated neem leaf extract for an easy, no-taste daily dose.",
                            ImageUrl = "/images/products/herbal-wellness/neem-capsules.jpg",
                            InStock = true,
                            Name = "Neem Capsules",
                            Popularity = 210,
                            Price = 260m,
                            Slug = "neem-capsules",
                            Unit = "60caps"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000070"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000015"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "A crunchy, spiced mix of sev, lentils and nuts fried fresh in small batches.",
                            ImageUrl = "/images/products/snacks-namkeen/mixture-namkeen.jpg",
                            InStock = true,
                            Name = "Mixture Namkeen",
                            Popularity = 211,
                            Price = 160m,
                            Slug = "mixture-namkeen",
                            Unit = "250g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000071"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000015"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Dry-roasted chickpeas, lightly salted for a crunchy, high-protein snack.",
                            ImageUrl = "/images/products/snacks-namkeen/roasted-chana.jpg",
                            InStock = false,
                            Name = "Roasted Chana",
                            Popularity = 216,
                            Price = 140m,
                            Slug = "roasted-chana",
                            Unit = "250g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000072"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000015"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Kerala-style banana chips, fried in coconut oil with a light sprinkle of salt.",
                            ImageUrl = "/images/products/snacks-namkeen/banana-chips.jpg",
                            InStock = true,
                            Name = "Banana Chips",
                            Popularity = 219,
                            Price = 150m,
                            Slug = "banana-chips",
                            Unit = "200g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000073"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000015"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Crisp, spiral-shaped rice-and-lentil murukku, fried fresh to order.",
                            ImageUrl = "/images/products/snacks-namkeen/murukku.jpg",
                            InStock = true,
                            Name = "Murukku",
                            Popularity = 222,
                            Price = 170m,
                            Slug = "murukku",
                            Unit = "250g"
                        },
                        new
                        {
                            Id = new Guid("d0a80001-0000-0000-0000-000000000074"),
                            CategoryId = new Guid("c0a80001-0000-0000-0000-000000000015"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Crunchy peanuts coated in a spiced gram-flour batter and fried whole.",
                            ImageUrl = "/images/products/snacks-namkeen/masala-peanuts.jpg",
                            InStock = true,
                            Name = "Masala Peanuts",
                            Popularity = 225,
                            Price = 130m,
                            Slug = "masala-peanuts",
                            Unit = "250g"
                        });
                });

            modelBuilder.Entity("FreshOMill.Domain.Catalog.Product", b =>
                {
                    b.HasOne("FreshOMill.Domain.Catalog.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
