// <auto-generated />
using System;
using FreshOMill.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FreshOMill.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260803184845_AddCategories")]
    partial class AddCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FreshOMill.Domain.Catalog.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0a80001-0000-0000-0000-000000000001"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 1,
                            ImageUrl = "/images/categories/wood-pressed-oils.jpg",
                            Name = "Wood Pressed Oils",
                            Slug = "wood-pressed-oils"
                        },
                        new
                        {
                            Id = new Guid("c0a80001-0000-0000-0000-000000000002"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 2,
                            ImageUrl = "/images/categories/flour-multigrain.jpg",
                            Name = "Flour & Multigrain",
                            Slug = "flour-multigrain"
                        },
                        new
                        {
                            Id = new Guid("c0a80001-0000-0000-0000-000000000003"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 3,
                            ImageUrl = "/images/categories/dry-fruits-dates.jpg",
                            Name = "Dry Fruits & Dates",
                            Slug = "dry-fruits-dates"
                        },
                        new
                        {
                            Id = new Guid("c0a80001-0000-0000-0000-000000000004"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 4,
                            ImageUrl = "/images/categories/nuts-seeds.jpg",
                            Name = "Nuts & Seeds",
                            Slug = "nuts-seeds"
                        },
                        new
                        {
                            Id = new Guid("c0a80001-0000-0000-0000-000000000005"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 5,
                            ImageUrl = "/images/categories/millets.jpg",
                            Name = "Millets",
                            Slug = "millets"
                        },
                        new
                        {
                            Id = new Guid("c0a80001-0000-0000-0000-000000000006"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 6,
                            ImageUrl = "/images/categories/spices.jpg",
                            Name = "Spices",
                            Slug = "spices"
                        },
                        new
                        {
                            Id = new Guid("c0a80001-0000-0000-0000-000000000007"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 7,
                            ImageUrl = "/images/categories/masalas.jpg",
                            Name = "Masalas",
                            Slug = "masalas"
                        },
                        new
                        {
                            Id = new Guid("c0a80001-0000-0000-0000-000000000008"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 8,
                            ImageUrl = "/images/categories/health-foods.jpg",
                            Name = "Health Foods",
                            Slug = "health-foods"
                        },
                        new
                        {
                            Id = new Guid("c0a80001-0000-0000-0000-000000000009"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 9,
                            ImageUrl = "/images/categories/coffee-tea.jpg",
                            Name = "Coffee & Tea",
                            Slug = "coffee-tea"
                        },
                        new
                        {
                            Id = new Guid("c0a80001-0000-0000-0000-000000000010"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 10,
                            ImageUrl = "/images/categories/pickles.jpg",
                            Name = "Pickles",
                            Slug = "pickles"
                        },
                        new
                        {
                            Id = new Guid("c0a80001-0000-0000-0000-000000000011"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 11,
                            ImageUrl = "/images/categories/rice-grains.jpg",
                            Name = "Rice & Grains",
                            Slug = "rice-grains"
                        },
                        new
                        {
                            Id = new Guid("c0a80001-0000-0000-0000-000000000012"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 12,
                            ImageUrl = "/images/categories/ghee-dairy.jpg",
                            Name = "Ghee & Dairy",
                            Slug = "ghee-dairy"
                        },
                        new
                        {
                            Id = new Guid("c0a80001-0000-0000-0000-000000000013"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 13,
                            ImageUrl = "/images/categories/honey-jaggery.jpg",
                            Name = "Honey & Jaggery",
                            Slug = "honey-jaggery"
                        },
                        new
                        {
                            Id = new Guid("c0a80001-0000-0000-0000-000000000014"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 14,
                            ImageUrl = "/images/categories/herbal-wellness.jpg",
                            Name = "Herbal & Wellness",
                            Slug = "herbal-wellness"
                        },
                        new
                        {
                            Id = new Guid("c0a80001-0000-0000-0000-000000000015"),
                            Created = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 15,
                            ImageUrl = "/images/categories/snacks-namkeen.jpg",
                            Name = "Snacks & Namkeen",
                            Slug = "snacks-namkeen"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
